# Generated by Django 4.1 on 2022-12-20 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("duration", models.DurationField()),
                ("premiere", models.DateField()),
                ("budget", models.IntegerField()),
                ("overview", models.TextField(blank=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="genres.genre"),
                ),
            ],
        ),
    ]
