# Generated by Django 4.1 on 2022-12-21 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("duration", models.CharField(max_length=127)),
                ("premiere", models.DateField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("overview", models.TextField(blank=True, null=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="genres.genre"
                    ),
                ),
            ],
        ),
    ]
